name: droxy
description: droxy is a pure dart multi channel websocket server.
version: 1.0.0
homepage: https://github.com/ilshookim/droxy

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # A package for manipulating stack traces and printing them readably.
  stack_trace: ^1.10.0

  # A string-based path manipulation library. All of the path operations you know and love, 
  # with solid support for Windows, POSIX (Linux and Mac OS X), and the web.
  path: ^1.8.0

  # A parser for YAML, a human-friendly data serialization standard
  yaml: ^3.1.0

  # Library for defining parsers for parsing raw command-line arguments into a set of options 
  # and values using GNU and POSIX style options.
  args: ^2.1.1

  # A model for web server middleware that encourages composition and easy reuse
  shelf: ^1.1.4

  # A shelf handler that wires up a listener for every connection.
  shelf_web_socket: ^1.0.1

dev_dependencies:
  # The Dart analyzer settings and best practices used internally at Google.
  pedantic: ^1.11.1
